version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: forum_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword   # Пароль для root
      MYSQL_DATABASE: forum_db            # База данных
      MYSQL_USER: user                    # Имя пользователя
      MYSQL_PASSWORD: userpassword        # Пароль пользователя
    ports:
      - "3307:3306"                       # Прокси порта MySQL
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Инициализация базы данных из init.sql
    networks:
      - forum_network

networks:
  forum_network:
    driver: bridge
